[package]
name = "game_of_life_evolution"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
lto = true
codegen-units = 1